//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogs
    {
        public blogs()
        {
            this.posts = new HashSet<posts>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string description { get; set; }
        public System.DateTime date_created { get; set; }
        public string admin_name { get; set; }
        public string admin_mail { get; set; }
    
        public virtual ICollection<posts> posts { get; set; }
    }
}
